# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DGIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.ASCIIUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=9)),
                ('is_laborantin', models.BooleanField(default=False)),
                ('curriculum', models.TextField(default='', null=True)),
                ('parcours_pro', models.TextField(default='', null=True, verbose_name='Parcours Professionnel')),
                ('parcours_aca', models.TextField(default='', null=True, verbose_name='Parcours Acad\xe9mique')),
                ('photo', models.ImageField(default='', null=True, upload_to='photos/')),
                ('slug', models.SlugField()),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_confirmed', models.BooleanField(default=False)),
                ('telephone', models.CharField(max_length=20)),
                ('compte', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriePublication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_departement', models.TextField(null=True)),
                ('mot_du_chef', models.TextField(null=True)),
                ('chef_de_departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgi.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=8)),
                ('is_initial', models.BooleanField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgi.Departement')),
            ],
        ),
        migrations.CreateModel(
            name='Laboratoire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150)),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgi.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50)),
                ('pages', models.CharField(max_length=50)),
                ('vues', models.IntegerField()),
                ('reference', models.URLField(null=True)),
                ('annee', models.IntegerField(null=True)),
                ('date_post', models.DateField(default=datetime.datetime(2017, 3, 13, 11, 19, 26, 594000, tzinfo=utc))),
                ('contenu', models.TextField(null=True)),
                ('auteurs', models.ManyToManyField(to='dgi.Agent')),
                ('categorie', models.ManyToManyField(to='dgi.CategoriePublication')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profession',
            name='specialite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dgi.Specialite'),
        ),
        migrations.AddField(
            model_name='formation',
            name='serie',
            field=models.ManyToManyField(to='dgi.Serie'),
        ),
        migrations.AddField(
            model_name='candidat',
            name='formation_asked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dgi.Formation'),
        ),
        migrations.AddField(
            model_name='agent',
            name='profession',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dgi.Profession'),
        ),
        migrations.AlterUniqueTogether(
            name='dgiuser',
            unique_together=set([('email',)]),
        ),
    ]
