# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0002_auto_20170313_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='telephone',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 3, 13, 11, 21, 19, 827000, tzinfo=utc)),
        ),
    ]
