# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0003_auto_20170313_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 3, 13, 12, 11, 0, 765000, tzinfo=utc)),
        ),
    ]
