# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 15:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0004_auto_20170313_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='encadrements',
            field=models.TextField(default='This is a text', null=True, verbose_name='Encadrements'),
        ),
        migrations.AddField(
            model_name='agent',
            name='enseignements',
            field=models.TextField(default='This is a text', null=True, verbose_name='Enseignements'),
        ),
        migrations.AddField(
            model_name='agent',
            name='recherches',
            field=models.TextField(default='This is a text', null=True, verbose_name='Recherches'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='parcours_aca',
            field=models.TextField(default='This is a text', null=True, verbose_name='Parcours Acad\xe9mique'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='parcours_pro',
            field=models.TextField(default='This is a text', null=True, verbose_name='Parcours Professionnel'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 3, 13, 15, 44, 42, 351000, tzinfo=utc)),
        ),
    ]
