# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 17:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0005_auto_20170313_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='cv',
            field=tinymce.models.HTMLField(default='<p></p>', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 3, 13, 17, 30, 40, 935000, tzinfo=utc)),
        ),
    ]
