# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0007_auto_20170314_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='curriculum',
            field=tinymce.models.HTMLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 3, 14, 10, 12, 31, 611000, tzinfo=utc)),
        ),
    ]
