# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0009_auto_20170314_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='libelle_reference',
            field=models.CharField(default='reference', max_length=50, verbose_name='Libelle R\xe9f\xe9rence'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 3, 14, 11, 38, 34, 344000, tzinfo=utc)),
        ),
    ]
