# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 11:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0011_auto_20170314_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 3, 14, 11, 47, 19, 213000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='titre',
            field=models.CharField(max_length=150),
        ),
    ]
