# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 11:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0012_auto_20170314_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(default='')),
                ('image', models.ImageField(upload_to=b'', verbose_name='Image de Couverture')),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='publication',
            name='contenu',
        ),
        migrations.AddField(
            model_name='publication',
            name='lien',
            field=models.URLField(default='', verbose_name='Lien vers Article'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 3, 15, 11, 29, 16, 700000, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='reference',
            field=models.URLField(null=True, verbose_name='Lien vers R\xe9f\xe9rence'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='vues',
            field=models.IntegerField(default=0),
        ),
    ]
