# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0013_auto_20170315_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(upload_to='information_image/', verbose_name='Image de Couverture'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 3, 15, 12, 17, 36, 295000, tzinfo=utc)),
        ),
    ]
