# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 12:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0015_auto_20170315_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='vue',
            field=models.IntegerField(default=0, verbose_name='Nombre de Consultations'),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 3, 15, 12, 58, 6, 598000, tzinfo=utc), verbose_name='Date de Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 3, 15, 12, 58, 6, 599000, tzinfo=utc)),
        ),
    ]
