# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 11:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0016_auto_20170315_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEDGI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('liens', models.URLField(verbose_name='Lien vers le service')),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='photo_du_chef',
            field=models.ImageField(default='', null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 19, 11, 37, 43, 123000, tzinfo=utc), verbose_name='Date de Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 6, 19, 11, 37, 43, 124000, tzinfo=utc)),
        ),
    ]
