# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 01:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0018_auto_20170620_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dgi.TypeInformation', verbose_name='Type Information'),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 20, 1, 31, 39, 507000, tzinfo=utc), verbose_name='Date de Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 6, 20, 1, 31, 39, 507000, tzinfo=utc)),
        ),
    ]
