# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 02:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0019_auto_20170620_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='fichier',
            field=models.FileField(null=True, upload_to='information_fichier/%Y/%m/%d', verbose_name='Fichier Associ\xe9'),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 20, 2, 14, 49, 627000, tzinfo=utc), verbose_name='Date de Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 6, 20, 2, 14, 49, 642000, tzinfo=utc)),
        ),
    ]
