# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-20 02:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0020_auto_20170620_0214'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoire',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 6, 20, 2, 49, 45, 49000, tzinfo=utc), verbose_name='Date de Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 6, 20, 2, 49, 45, 50000, tzinfo=utc)),
        ),
    ]
