# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-08-29 15:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dgi', '0022_auto_20170620_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 8, 29, 15, 19, 21, 425000, tzinfo=utc), verbose_name='Date de Publication'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='date_post',
            field=models.DateField(default=datetime.datetime(2017, 8, 29, 15, 19, 21, 426000, tzinfo=utc)),
        ),
    ]
